In [1]:
import pandas as pd

# Define data path
data_path = '/Users/Mach/dev/aps/data/2026_Dmodel_data'

In [2]:
# Read car parquet file
car_df = pd.read_parquet(f'{data_path}/master_dataset_car.parquet')
print(f'Car dataframe shape: {car_df.shape}')
print(f'Car dataframe columns: {car_df.columns.tolist()}')
car_df.head()

Car dataframe shape: (22705842, 406)
Car dataframe columns: ['vin_date', 'vin', 'zip', 'py', 'companyid', 'reference_num', 'policyid', 'poleffdt', 'poleffdt_imps', 'polexpdt_raw', 'polexpdt_imps', 'coveffdt_raw', 'coveffdt_imps', 'covexpdt_raw', 'covexpdt_imps', 'origpoleffdt_raw', 'origpoleffdt_imps', 'pol_tenure_cal', 'st_raw', 'cbistier_raw', 'cbistier_imps', 'late_payments_raw', 'late_payments_imps', 'credit_raw', 'credit_imps', 'vehicle_use_raw', 'veh_use_commute_ind', 'veh_use_business_ind', 'veh_use_farm_ind', 'veh_count_raw', 'veh_count_imps', 'driver_count_raw', 'driver_count_imps', 'pol_veh_driver_ratio_cal', 'model_year_raw', 'multi_policy_discount_raw', 'multi_pol_yes_cal', 'multi_pol_unknown_cal', 'limit_person_bi_raw', 'limit_person_bi_imps', 'limit_acc_bi_raw', 'limit_acc_bi_imps', 'veh_limit_bi_acc_ratio_cal', 'limit_csl_raw', 'limit_csl_imps', 'limit_pd_raw', 'limit_pd_imps', 'limit_med_raw', 'limit_med_imps', 'limit_pip_raw', 'limit_pip_imps', 'limit_um_raw', 'limit_um_imps', 'limit_uim_raw', 'limit_uim_imps', 'ded_coll_raw', 'ded_coll_imps', 'ded_comp_raw', 'ded_comp_imps', 'DrvAge_raw', 'DrvAge_imps', 'gender_male_ind', 'married_ind', 'NumMinAcc_raw', 'NumMinAcc_imps', 'NumMajinAcc_raw', 'NumMajinAcc_imps', 'NumSpdViol_raw', 'NumSpdViol_imps', 'NumMinViol_raw', 'NumMinViol_imps', 'NumMajViol_raw', 'NumMajViol_imps', 'driver_has_acc_any_ind', 'driver_has_vio_any_ind', 'ee_bi_raw', 'ee_bi_imps', 'ee_pd_raw', 'ee_pd_imps', 'ee_pip_raw', 'ee_pip_imps', 'ee_med_raw', 'ee_med_imps', 'ee_um_raw', 'ee_um_imps', 'ee_uim_raw', 'ee_uim_imps', 'ee_coll_imps', 'ee_coll_imp_imps', 'ee_comp_raw', 'ee_comp_imps', 'ee_raw', 'ee_imps', 'incurred_raw_bi_raw', 'incurred_raw_bi_imps', 'incurred_raw_pd_raw', 'incurred_raw_pd_imps', 'incurred_raw_pip_raw', 'incurred_raw_pip_imps', 'incurred_raw_med_cal', 'incurred_raw_med_cal_imps', 'incurred_raw_um_raw', 'incurred_raw_um_imps', 'incurred_raw_uim_raw', 'incurred_raw_uim_imps', 'incurred_raw_coll_raw', 'incurred_raw_coll_imps', 'incurred_raw_comp_raw', 'incurred_raw_comp_imps', 'incloss_raw', 'incloss_imps', 'claim_count_bi_raw', 'claim_count_bi_imps', 'claim_count_pd_raw', 'claim_count_pd_imps', 'claim_count_pip_raw', 'claim_count_pip_imps', 'claim_count_med_cal', 'claim_count_med_cal_imps', 'claim_count_um_raw', 'claim_count_um_imps', 'claim_count_uim_raw', 'claim_count_uim_imps', 'claim_count_coll_raw', 'claim_count_coll_imps', 'claim_count_comp_raw', 'claim_count_comp_imps', 'claim_count_raw', 'claim_count_imps', 'ep_bi_raw', 'ep_bi_imps', 'ep_pd_raw', 'ep_pd_imps', 'ep_pip_raw', 'ep_pip_imps', 'ep_med_raw', 'ep_med_imps', 'ep_um_raw', 'ep_um_imps', 'ep_uim_raw', 'ep_uim_imps', 'ep_coll_raw', 'ep_coll_imps', 'ep_comp_raw', 'ep_comp_imps', 'dml_make_raw', 'dml_model_raw', 'dml_body_style_raw', 'dml_engine_raw', 'dml_year_raw', 'dml_year_imps', 'gvw_num_imps', 'amc_annual_mileage_estimate_raw', 'amc_ame_rounded_imps', 'amc_modeled_annual_mileage_raw', 'amc_mam2_rounded_imps', 'owt_current_ownership_type_raw', 'owt_comm_ind', 'owt_leasepers_ind', 'owt_number_of_titling_transactions_raw', 'owt_number_of_titling_transactions_imps', 'owh_loo_days_raw', 'owh_loo_days_imps', 'owh_loo_years_cal', 'owh_loo_years_imp', 'cef_est_curr_mi_grp_raw', 'cef_est_curr_mi_grp_imps', 'cef_ann_mi_grp_raw', 'cef_ann_mi_grp_imps', 'cef_owner_count_raw', 'cef_owner_count_imps', 'days_since_first_rollback_cal', 'days_since_first_rollback_imp', 'days_since_first_airbag_deployed_cal', 'days_since_first_airbag_deployed_imps', 'days_since_first_commercial_use_cal', 'days_since_first_commercial_use_imps', 'days_since_first_corporate_use_cal', 'days_since_first_corporate_use_imps', 'days_since_first_failed_emissions_cal', 'days_since_first_failed_emissions_imps', 'days_since_first_fleet_cal', 'days_since_first_fleet_imps', 'days_since_first_government_use_cal', 'days_since_first_government_use_imps', 'days_since_first_lease_cal', 'days_since_first_lease_imps', 'days_since_first_rental_cal', 'days_since_first_rental_imps', 'days_since_first_repossession_cal', 'days_since_first_repossession_imps', 'days_since_first_safety_failed_cal', 'days_since_first_safety_failed_imps', 'days_since_first_scrapped_cal', 'days_since_first_scrapped_imps', 'days_since_first_sev_frame_dam_prob_cal', 'days_since_first_sev_frame_dam_prob_imps', 'days_since_first_taxi_cal', 'days_since_first_taxi_imps', 'days_since_first_salvage_auction_cal', 'days_since_first_salvage_auction_imps', 'days_since_first_stolen_cal', 'days_since_first_stolen_imps', 'days_since_first_total_loss_us_cal', 'days_since_first_total_loss_us_imps', 'cef_first_branded_ind', 'cef_first_branded_nul', 'cef_first_cpo_ind', 'cef_first_cpo_nul', 'cef_first_poten_dam_ind', 'cef_first_poten_dam_nul', 'cef_first_sev_prob_ind', 'cef_first_sev_prob_nul', 'cef_lien_holder_ind', 'cef_lien_holder_nul', 'vc_acceleration_0_60_raw', 'vc_acceleration_0_60_impa', 'vc_active_collision_avoidance_system_raw', 'vc_active_driving_assistance_raw', 'vc_active_parking_assistance_raw', 'vc_adaptive_cruise_control_raw', 'vc_antitheft_key_raw', 'vc_aspiration_raw', 'vc_aspiration_forced_induction_ind', 'vc_audible_forward_collision_warning_raw', 'vc_auto_dimming_rearview_mirror_raw', 'vc_auto_dimming_side_mirrors_raw', 'vc_auto_hazard_flashers_raw', 'vc_auto_start_stop_raw', 'vc_automatic_crash_notification_raw', 'vc_automatic_emergency_braking_raw', 'vc_automatic_emergency_steering_raw', 'vc_automatic_high_beams_raw', 'vc_backup_camera_raw', 'vc_bed_length_raw', 'vc_bed_length_impa', 'vc_blind_spot_camera_raw', 'vc_blind_spot_warning_raw', 'vc_camera_raw', 'vc_camera_front_raw', 'vc_camera_side_raw', 'vc_camera_washer_raw', 'vc_cargo_van_raw', 'vc_center_locking_differential_raw', 'vc_cornering_brake_control_raw', 'vc_cornering_lights_raw', 'vc_crash_sensing_door_locks_raw', 'vc_crash_sensors_raw', 'vc_cross_traffic_warning_raw', 'vc_crumple_zones_raw', 'vc_curb_weight_raw', 'vc_curb_weight_impa', 'vc_cylinders_raw', 'vc_daytime_running_lights_raw', 'vc_displacement_raw', 'vc_doors_raw', 'vc_doors_impm', 'vc_drive_type_4wd_ind', 'vc_drive_type_4x2_ind', 'vc_drive_type_4x4_ind', 'vc_drive_type_awd_ind', 'vc_drive_type_fwd_ind', 'vc_drive_type_rwd_ind', 'vc_driver_attention_system_raw', 'vc_dvd_player_raw', 'vc_electronic_4wd_selector_raw', 'vc_electronic_braking_system_raw', 'vc_engine_type_hybrid_electric_ind', 'vc_engine_valves_raw', 'vc_fog_lights_raw', 'vc_fog_lights_rear_raw', 'vc_forward_automatic_emergency_braking_raw', 'vc_forward_collision_warning_raw', 'vc_front_cross_traffic_warning_raw', 'vc_front_parking_sensors_raw', 'vc_fuel_tank_capacity_raw', 'vc_fuel_tank_capacity_impa', 'vc_fuel_type_raw', 'vc_fuel_diesel_ind', 'vc_glass_roof_raw', 'vc_gross_combined_weight_raw', 'vc_gross_combined_weight_impa', 'vc_ground_clearance_raw', 'vc_ground_clearance_impa', 'vc_headlights_auto_on_off_raw', 'vc_headlights_leveling_raw', 'vc_headlights_wiper_activated_raw', 'vc_heated_side_mirrors_raw', 'vc_heated_steering_wheel_raw', 'vc_heated_washer_jets_raw', 'vc_height_raw', 'vc_height_impa', 'vc_hill_ascent_assist_raw', 'vc_horsepower_raw', 'vc_derived_hp_to_volume_cal', 'vc_derived_hp_to_density_cal', 'vc_derived_hp_to_turn_cal', 'vc_derived_hp_to_weight_cal', 'vc_derived_turn_to_length_cal', 'vc_derived_turn_to_width_cal', 'vc_derived_length_to_rows_cal', 'vc_derived_stability_val_cal', 'vc_derived_rollover_risk_cal', 'vc_infotainment_screen_cal', 'vc_instrumentation_display_cal', 'vc_integrated_wifi_raw', 'vc_interior_volume_raw', 'vc_interior_volume_nul', 'vc_interior_volume_impa', 'vc_lane_departure_warning_raw', 'vc_lane_keeping_assistance_raw', 'vc_length_raw', 'vc_length_impa', 'vc_mild_hybrid_raw', 'vc_msrp_raw', 'vc_msrp_impa', 'vc_navigation_touchscreen_raw', 'vc_off_road_lights_raw', 'vc_parking_collision_warning_raw', 'vc_parking_sensors_raw', 'vc_passenger_volume_raw', 'vc_passenger_volume_impa', 'vc_passive_collision_avoidance_system_raw', 'vc_payload_capacity_raw', 'vc_payload_capacity_impa', 'vc_pedestrian_detection_raw', 'vc_post_crash_fuel_cutoff_raw', 'vc_power_folding_side_mirrors_raw', 'vc_power_sunroof_raw', 'vc_precollision_system_raw', 'vc_premium_audio_raw', 'vc_premium_wheels_raw', 'vc_rear_cross_traffic_warning_raw', 'vc_rear_parking_sensors_raw', 'vc_rear_window_defogger_raw', 'vc_rear_wiper_raw', 'vc_rear_wiper_automatic_raw', 'vc_remote_engine_start_raw', 'vc_reverse_automatic_emergency_braking_raw', 'vc_satellite_radio_raw', 'vc_seating_capacity_raw', 'vc_seating_capacity_impm', 'vc_seating_rows_raw', 'vc_seating_rows_impm', 'vc_luxury_flag_ind', 'vc_semiautomatic_parking_system_raw', 'vc_side_mirror_turn_signals_raw', 'vc_side_window_defogger_raw', 'vc_softtop_raw', 'vc_speed_sensitive_volume_raw', 'vc_subwoofer_raw', 'vc_sunroof_raw', 'vc_surround_sound_raw', 'vc_tactile_forward_collision_warning_raw', 'vc_taillights_led_raw', 'vc_tinted_windows_raw', 'vc_torque_raw', 'vc_torque_nul', 'vc_touch_screen_raw', 'vc_towing_capacity_raw', 'vc_towing_capacity_impa', 'vc_traffic_sign_recognition_raw', 'vc_trailer_assist_raw', 'vc_transmission_type_automatic_ind', 'vc_transmission_type_continuously_variable_ind', 'vc_transmission_type_manual_ind', 'vc_turning_circle_raw', 'vc_turning_circle_impa', 'vc_variable_power_steering_raw', 'vc_vehicle_immobilizer_raw', 'vc_veh_type_car_ind', 'vc_veh_type_suv_ind', 'vc_veh_type_van_ind', 'vc_veh_type_truck_ind', 'vc_video_display_raw', 'vc_video_system_raw', 'vc_visual_forward_collision_warning_raw', 'vc_wheelbase_raw', 'vc_wheelbase_impa', 'vc_width_raw', 'vc_width_impa', 'vc_wipers_automatic_raw', 'vc_wipers_heated_raw', 'vc_wipers_speed_sensitive_raw', 'insstate', 'zpop', 'zhu', 'zarea', 'pop_per_hu', 'zarealand', 'zip_pop_pct', 'zip_pop_dens', 'latitude', 'longitude', 'territory_bi', 'territory_coll', 'territory_core3', 'territory_otc', 'territory_pd', 'territory_pip', 'A1_Score', 'B2_score', 'C1_Collision_Score', 'C1_Comprehensive_Score', 'C1_First_Party_Liability_Score', 'C1_Third_Party_Liability_Score']

,vin_date,vin,zip,py,companyid,reference_num,policyid,poleffdt,poleffdt_imps,polexpdt_raw,...,territory_core3,territory_otc,territory_pd,territory_pip,A1_Score,B2_score,C1_Collision_Score,C1_Comprehensive_Score,C1_First_Party_Liability_Score,C1_Third_Party_Liability_Score
0,KMHWF35H45A178516_04-26-2022,KMHWF35H45A178516,43613,2022,C172621,C172621,H246865,2022-04-26,2022-04-26,2023-04-26,...,OH1,OH4,OH1,OH0,479.0,391.0,665.0,795.0,221.0,569.0
1,KMHWF35H75A128502_11-21-2020,KMHWF35H75A128502,78758,2020,C117026,C117026,30623212,2020-11-21,2020-11-21,2021-05-21,...,TX3,TX5,TX3,TX1,479.0,353.0,625.0,755.0,229.0,574.0
2,KMHD35LE5DU068088_05-03-2020,KMHD35LE5DU068088,92315,2020,C117026,C117026,22150816,2020-05-03,2020-05-03,2021-05-03,...,CA1,CA2,CA2,CA0,483.0,553.0,637.0,752.0,499.0,611.0
3,KMHD35LE5DU047158_05-30-2021,KMHD35LE5DU047158,30519,2021,C147884,C147884,91111025KG,2021-05-30,2021-05-30,2021-11-30,...,GA2,GA3,GA2,GA0,483.0,338.0,637.0,752.0,499.0,611.0
4,KMHD35LE5DU082332_11-17-2019,KMHD35LE5DU082332,8075,2019,C090317,C090317,HPA00001212784,2019-11-17,2019-11-17,2020-05-17,...,NJ5,NJ5,NJ4,NJ4,483.0,495.0,647.0,756.0,491.0,605.0

In [ ]:
# Read VIN_BSST parquet file
vin_bsst_df = pd.read_parquet(f'{data_path}/VIN_BSST.parquet')
print(f'VIN_BSST dataframe shape: {vin_bsst_df.shape}')
print(f'VIN_BSST dataframe columns: {vin_bsst_df.columns.tolist()}')
vin_bsst_df.head()

VIN_BSST dataframe shape: (26310207, 2)
VIN_BSST dataframe columns: ['VIN', 'BODY_STYLE_SEGMENT_BODY_TYPE']

                 VIN BODY_STYLE_SEGMENT_BODY_TYPE
0  1B3HB48B88D587726          Basic Economy (Car)
1  1C6RR7ST4JS291614              Fullsize Pickup
2  5J6RW2H84LA025942                Sport Utility
3  JN8AS5MV5AW136578                Sport Utility
4  5NMS3CAD0LH161245                Sport Utility

In [ ]:
# VIN is a column by itself, so dont worry. 
# Extract VIN from vin_date column in car dataframe
# vin_date typically contains VIN and date separated by underscore
# car_df['vin'] = car_df['vin_date'].str.split('_').str[0]
# print(f'Sample vin_date values: {car_df["vin_date"].head().tolist()}')
# print(f'Extracted VIN values: {car_df["vin"].head().tolist()}')

In [4]:
# Get unique VINs from car dataframe
car_vins = set(car_df['vin'].unique())
print(f'Total unique VINs in car data: {len(car_vins)}')

# Get unique VINs from BSST dataframe
# Check the column name for VIN in BSST
print(f'VIN_BSST columns: {vin_bsst_df.columns.tolist()}')

Total unique VINs in car data: 6591774
VIN_BSST columns: ['VIN', 'BODY_STYLE_SEGMENT_BODY_TYPE']

In [5]:
# Find VINs without BSST
# Assuming VIN column in BSST is 'VIN' or 'vin'
vin_col = 'VIN' if 'VIN' in vin_bsst_df.columns else 'vin'
bsst_vins = set(vin_bsst_df[vin_col].unique())
print(f'Total unique VINs in BSST data: {len(bsst_vins)}')

# VINs in car data that don't have BSST
vins_without_bsst = car_vins - bsst_vins
print(f'\n=== RESULT ===' )
print(f'Number of VINs without BSST: {len(vins_without_bsst)}')
print(f'Percentage of VINs without BSST: {len(vins_without_bsst)/len(car_vins)*100:.2f}%')

Total unique VINs in BSST data: 22225676

=== RESULT ===
Number of VINs without BSST: 13935
Percentage of VINs without BSST: 0.21%